kind: Deployment
apiVersion: apps/v1
metadata:
   name: webapp
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: webapp
    template:
       metadata:
         labels:
           app: webapp
       spec:
        containers:
         - name: webapp
           image: bhagyash654/project-demo
           imagePolicy: Always
           ports:
           - containerPort: 80
