kind: Service
apiVersion: v1
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 80
  selector:
     app.kubernetes.io/name: webapp 
  type: LoadBalancer